version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

workflows:
  build:
    jobs:
      - node/run:
          npm-run: build

      - node/test

      - heroku/deploy-via-git:
          requires:
            - node/run
            - node/test
          app-name: "joke-app-mm"
